npcPlayer:
  - npcId: "madeline"
    variant: "madeline"
    death_link:
      lead_by_player: true
      lead_to_player: true

  - npcId: "badeline"
    variant: "badeline"
    death_link:
      lead_by_player: false
      lead_to_player: false

  - npcId: "silvy"
    variant: "Silvy_White"

  - npcId: "rucia"
    variant: "Rucia_White"

  - npcId: "neuro"
    variant: "Neuro_Sama"

  - npcId: "niko"
    variant: "Zaro_Niko"
