- npcPlayer:
    npcId: "madeline"
    variant: "madeline"

- npcPlayer:
    npcId: "badeline"
    variant: "badeline"

- npcPlayer:
    npcId: "silvy"
    variant: "Silvy_White"

- npcPlayer:
    npcId: "rucia"
    variant: "Rucia_White"

- npcPlayer:
    npcId: "neuro"
    variant: "Neuro_Sama"

- npcPlayer:
    npcId: "niko"
    variant: "Zaro_Niko"